---@meta
---@module 'ui.kit.@types'

--- Semantic highlight groups of a theme. Each is either a highlight-group name
--- to link to (string) or an explicit highlight spec (Lib.Highlight.Opts).
---@class Ui.Kit.ThemeHighlights
---@field normal    string|Lib.Highlight.Opts # body            (default: link NormalFloat)
---@field border    string|Lib.Highlight.Opts # border          (default: link FloatBorder)
---@field title     string|Lib.Highlight.Opts # title           (default: link FloatTitle)
---@field selection string|Lib.Highlight.Opts # current item    (default: link PmenuSel)
---@field accent    string|Lib.Highlight.Opts # focused/active  (default: link Special)
---@field muted     string|Lib.Highlight.Opts # hints/secondary (default: link Comment)
---@field error     string|Lib.Highlight.Opts # error/destructive (default: link DiagnosticError)
---@field flash     string|Lib.Highlight.Opts # momentary pick feedback (default: link IncSearch)
---@field hover     string|Lib.Highlight.Opts # row under the mouse pointer (default: link Visual)

--- A resolved theme: design tokens read by every component.
---@class Ui.Kit.Theme
---@field border string|string[]                 # nvim_open_win border
---@field ascii_border boolean                   # true when the border uses ASCII glyphs
---@field padding { x: integer, y: integer }
---@field zindex { base: integer, popup: integer, toast: integer, menu: integer }
---@field title_pos "left"|"center"|"right"
---@field dims { min_w: integer, max_w: integer, min_h: integer, max_h: integer }
---@field hl Ui.Kit.ThemeHighlights

--- A theme argument accepted by surfaces/components: a preset name, a partial
--- override table (deep-merged over the active default), or nil (active default).
---@alias Ui.Kit.ThemeArg string|table|nil

--- Options for `kit.surface.open`.
---@class Ui.Kit.SurfaceOpts
---@field lines? string[]        # initial content
---@field theme? Ui.Kit.ThemeArg
---@field title? string
---@field title_pos? "left"|"center"|"right"  # overrides the theme
---@field width? integer
---@field height? integer
---@field relative? "editor"|"cursor"|"win"
---@field win? integer          # anchor window, required when relative = "win"
---@field anchor? "NW"|"NE"|"SW"|"SE"  # default "NW", except cursor/mouse auto-flips to "SW" near the bottom of the screen
---@field row? integer
---@field col? integer
---@field zindex? integer        # overrides the theme's popup zindex
---@field enter? boolean         # focus the new window (default true)
---@field focusable? boolean
---@field nice_quit? boolean|Lib.Window.NiceQuitOpts  # bind q/<Esc> to close
---@field filetype? string
---@field modifiable? boolean
---@field on_close? fun()        # called once when the window closes (any cause)
---@field wo? table<string, any>
---@field bo? table<string, any>

--- Handle returned by `kit.surface.open` — a themed float + lifecycle.
---@class Ui.Kit.Surface
---@field winid integer
---@field bufnr integer
---@field set_lines fun(self: Ui.Kit.Surface, lines: string[])
---@field set_title fun(self: Ui.Kit.Surface, title: string|nil)
---@field focus fun(self: Ui.Kit.Surface)
---@field on_close fun(self: Ui.Kit.Surface, cb: fun())
---@field is_valid fun(self: Ui.Kit.Surface): boolean
---@field close fun(self: Ui.Kit.Surface)

--- Options for the `note` component / `kit.popup({ type = "note" })`.
---@class Ui.Kit.NoteOpts
---@field title? string
---@field message string|string[]
---@field theme? Ui.Kit.ThemeArg
---@field timeout? integer        # auto-close after N ms (0/nil = stay)
---@field width? integer
---@field height? integer
---@field relative? "editor"|"cursor"|"win"

--- Options for the `viewer` component / `kit.popup({ type = "viewer" })`.
---@class Ui.Kit.ViewerOpts
---@field title? string
---@field lines? string[]                                # alias: message
---@field message? string|string[]
---@field theme? Ui.Kit.ThemeArg
---@field width? integer
---@field height? integer
---@field relative? "editor"|"cursor"|"win"
---@field enter? boolean                                  # focus + allow scrolling (default true)
---@field filetype? string
---@field close_on_focus_lost? boolean                    # dismiss on WinLeave/BufLeave (default true)

--- Options for `message_log` -- a scrollable, time-ordered, paginated,
--- collapsible entry list popup. Knows nothing about where entries come
--- from; `time_ms` on an entry just needs to share a clock with `now_ms`
--- and the other entries (monotonic `vim.uv.hrtime()/1e6` or epoch, either
--- works -- this module only ever subtracts two of the caller's own values).
---@class Ui.Kit.MessageLog.Entry
---@field time_ms? number
---@field level? integer                                  # vim.log.levels value; only used to pick a highlight
---@field content string
---@class Ui.Kit.MessageLog.Opts
---@field title? string
---@field entries? Ui.Kit.MessageLog.Entry[]               # initial content, oldest first
---@field order? "newest_last"|"newest_first"              # default "newest_last"
---@field collapsed_default? boolean
---@field load_more? fun(direction: "older"|"newer"): Ui.Kit.MessageLog.Entry[]  # pagination; omit to disable
---@field max_entries? integer                            # cap on entries held locally; oldest dropped past it (default: unbounded) -- bounds both memory and the cost of each redraw for a popup left open against a live feed
---@field format_entry_time? fun(entry: Ui.Kit.MessageLog.Entry, now_ms: number): string  # default: "Ns ago"/"Nm Ns ago"
---@field now_ms? fun(): number                            # default: vim.uv.hrtime()/1e6
---@field extra_cheatsheet_lines? string[]                 # appended to the built-in `?` key list
---@field theme? Ui.Kit.ThemeArg
---@field width? integer
---@field height? integer
---@field relative? "editor"|"cursor"|"win"
---@field filetype? string
---@field close_on_focus_lost? boolean                     # default true

---@class Ui.Kit.MessageLog.Handle
---@field append fun(self: Ui.Kit.MessageLog.Handle, new_entries: Ui.Kit.MessageLog.Entry[])
---@field load_more fun(self: Ui.Kit.MessageLog.Handle, direction: "older"|"newer")
---@field set_collapsed fun(self: Ui.Kit.MessageLog.Handle, value?: boolean)
---@field on_close fun(self: Ui.Kit.MessageLog.Handle, cb: fun())
---@field close fun(self: Ui.Kit.MessageLog.Handle)

---@class Ui.Kit.MessageLogModule
---@field open fun(opts: Ui.Kit.MessageLog.Opts): Ui.Kit.MessageLog.Handle|nil

--- One entry of a `kit.menu`. Two shapes are accepted, because this component
--- doubles as the native renderer for `ui.contextmenu`: the kit's own
--- `label`/`action` pair, and nvzone/menu's `name`/`cmd` (with `items` for a
--- nested fly-out, `rtxt` for a right-aligned hint, `hl` for a row colour).
--- `{ name = "separator" }` draws an inert divider.
---@class Ui.Kit.MenuItem
---@field label? string      # display text (leading/trailing space is trimmed)
---@field action? fun()      # callback run when the item is picked (alias: cb)
---@field name? string       # display text, nvzone/menu spelling (or the literal "separator")
---@field cmd? fun()|string  # leaf action, nvzone/menu spelling: callback or Ex command string
---@field items? Ui.Kit.MenuItem[]  # nested fly-out (mutually exclusive with cmd/action)
---@field rtxt? string       # right-aligned hint text (usually a keymap)
---@field icon? string       # leading glyph, drawn in a column of its own -- NOT part of `label`
---@field icon_hl? string    # highlight group for the icon (default: `hl`, else KitAccent)
---@field hl? string         # highlight group for this row's label

--- Options for `kit.menu`.
---@class Ui.Kit.MenuOpts
---@field items Ui.Kit.MenuItem[]
---@field title? string
---@field theme? Ui.Kit.ThemeArg  # default: the `menu` preset (coloured frame)
---@field relative? "editor"|"cursor"|"win"|"mouse"
---@field win? integer       # anchor window; implies relative = "win" when `relative` is unset
---@field anchor? "NW"|"NE"|"SW"|"SE"  # which corner sits at (row, col); default "NW" (auto-flips to "SW" near the bottom of the screen for cursor/mouse)
---@field row? integer       # explicit placement, paired with `relative`
---@field col? integer
---@field mouse? boolean     # shorthand for `relative = "mouse"` (nvzone/menu's spelling)
---@field hide_cursor? boolean          # blank the terminal cursor while open; default true
---@field single_click? boolean         # one left click picks, a click outside dismisses; default true
---@field close_on_focus_lost? boolean  # dismiss when focus moves elsewhere; default true
---@field flash_on_select? boolean      # light the picked row before acting; default true
---@field flash_ms? integer             # how long that lasts; default 100, <= 0 disables
---@field hover? boolean                # follow the mouse without a click, via 'mousemoveevent' + <MouseMove>; default true
---@field group_style? "box"|"header"|"plain"  # how a group of items is drawn; default "box"
---@field submenu_marker? string        # glyph marking a nested entry; default "→"

--- One `kit.select`/`kit.popup({type="select"})` item, for a multi-line entry
--- with per-column custom highlight groups (worked example:
--- `docs/EXAMPLES/kit-select.lua`). A plain string item still works
--- unchanged -- this is opt-in per item.
---@class Ui.Kit.RichItem
---@field lines string[]                       # >=1 line; buffer content for this item
---@field highlights? Ui.Kit.ItemHighlight[]
---@field anchor? integer                      # 0-based line (within `lines`) the cursor lands on; default 0
---@field selectable? boolean                  # false = inert decoration (separator, heading): skipped by navigation, <CR> does nothing; default true
---@field hover_start_col? integer               # byte column (line 0) the hover paint starts at; nil = column 0
---@field hover_end_col? integer                # byte column (line 0) the hover paint stops at; nil = the whole row width (chooser.lua's paint_hover)

--- One highlight span within a `Ui.Kit.RichItem`.
---@class Ui.Kit.ItemHighlight
---@field line integer        # 0-based, within this item's `lines`
---@field col_start? integer  # default 0
---@field col_end? integer    # default: end of that line
---@field hl_group string

--- One field of a `kit.form`. `name` is the key its answer is stored under
--- in the result table handed to `on_submit`.
---@class Ui.Kit.FormField
---@field name string                     # result table key
---@field label? string                   # alias: prompt
---@field prompt? string
---@field default? string
---@field required? boolean               # <Esc> aborts the whole form instead of skipping this field
---@field expand_env? boolean             # run the answer through lib.nvim.cross.fs.expand_path
---@field theme? Ui.Kit.ThemeArg       # overrides opts.theme for this field
---@field width? integer                  # overrides opts.width for this field
---@field relative? "editor"|"cursor"|"win"  # overrides opts.relative for this field

--- Options for `kit.form` / `kit.popup({ type = "form" })`.
---@class Ui.Kit.FormOpts
---@field fields Ui.Kit.FormField[]
---@field theme? Ui.Kit.ThemeArg
---@field width? integer
---@field relative? "editor"|"cursor"|"win"
---@field back? boolean                    # opt-in back navigation: <BS> on an empty field / <S-Tab> / <C-p> / [← Back] reopen the previous field with its answer; "(i/n)" in the title; a [← Back] [Skip] [Next ↵] button row under the field (default off: nothing below changes)
---@field on_submit fun(values: table<string, string>)
---@field on_cancel? fun()

--- One field of a `kit.sheet`. `name` is the key its answer is stored under in
--- the table handed to `on_submit`.
---@class Ui.Kit.SheetField
---@field name string                     # result table key
---@field label? string                   # the row's label (alias: prompt; default: name)
---@field prompt? string
---@field kind? "text"|"select"           # default "text"; "select" needs `choices`
---@field default? string                 # text: the initial value; select: the choice shown first
---@field choices? string[]               # select: the fixed choices (h/l cycle, <CR>/<Space> open kit.select)
---@field required? boolean               # a blank value is rejected
---@field validate? fun(value: string): boolean?, string?  # truthy ok accepts; falsy rejects with the message (not called for an empty optional field)
---@field live? boolean                   # validate on every edit, not only after the field has been left
---@field expand_env? boolean             # text: run the answer through lib.nvim.cross.fs.expand_path
---@field completion? string              # text: a getcompletion() type; <Tab> completes
---@field secret? boolean                 # text: mask the value as you type
---@field mask? string                    # placeholder char when secret = true (default "*")

--- Options for `kit.sheet` / `kit.popup({ type = "sheet" })`.
---@class Ui.Kit.SheetOpts
---@field fields Ui.Kit.SheetField[]
---@field title? string
---@field submit_label? string             # default "Submit"
---@field cancel_label? string             # default "Cancel"
---@field required_message? string         # shown under a blank required field (default "required")
---@field focus? string|integer            # field (name or position) the sheet opens on; default the first
---@field theme? Ui.Kit.ThemeArg
---@field width? integer                   # default 60 (never wider than the editor)
---@field relative? "editor"|"cursor"|"win"  # default "editor" (centered, and kept centered as it grows)
---@field on_submit fun(values: table<string, string>)
---@field on_cancel? fun()

--- What `kit.sheet` returns: its surface plus four methods, for driving it from
--- code and from specs.
---@class Ui.Kit.Sheet : Ui.Kit.Surface
---@field submit fun(self: Ui.Kit.Sheet)                       # as if Submit were pressed (validation included)
---@field cancel fun(self: Ui.Kit.Sheet)                       # as if <Esc> were pressed
---@field focus_field fun(self: Ui.Kit.Sheet, which: string|integer)  # focus a field by name or position
---@field state fun(self: Ui.Kit.Sheet): { focus: string, values: table<string, string>, errors: table<string, string> }  # focus = a field name, "submit" or "cancel"

--- Options for `kit.input` / `kit.popup({ type = "input" })`.
---@class Ui.Kit.InputOpts
---@field title? string                   # alias: prompt
---@field prompt? string
---@field default? string
---@field theme? Ui.Kit.ThemeArg
---@field width? integer
---@field relative? "editor"|"cursor"|"win"
---@field expand_env? boolean              # run the submitted line through lib.nvim.cross.fs.expand_path
---@field secret? boolean                  # mask the input as you type (vim.fn.inputsecret replacement)
---@field mask? string                     # placeholder char when secret = true (default "*")
---@field completion? string               # a getcompletion() type ("file", "dir", ...); <Tab> completes (vim.fn.input's completion="file" replacement)
---@field on_back? fun(line: string)        # opt-in: <BS> on an EMPTY line, <S-Tab> and <C-p> close the prompt and call this with the line as it stood (kit.form's `back` uses it)
---@field buttons? Ui.Kit.InputButton[]     # opt-in: a clickable row of `[ Label ]` buttons under the field (the prompt is then two lines tall)
---@field on_submit? fun(line: string)      # <CR>
---@field on_cancel? fun()                  # <Esc>

--- One button of `Ui.Kit.InputOpts.buttons`. `id` says what pressing it does:
--- `submit` is `<CR>`, `skip` is `<Esc>`, `back` is the `on_back` keys (dropped
--- when there is no `on_back`).
---@class Ui.Kit.InputButton
---@field id "back"|"skip"|"submit"
---@field label string

--- Where one button of a row sits: 0-based buffer row and byte columns
--- (`end_col` exclusive) -- what an extmark takes, and what a click is tested against.
---@class Ui.Kit.ButtonRange
---@field row integer
---@field start_col integer
---@field end_col integer

--- Options for `kit.live_input` / `kit.popup({ type = "live_input" })`.
---@class Ui.Kit.LiveInputOpts
---@field title? string                   # alias: prompt
---@field prompt? string
---@field default? string
---@field theme? Ui.Kit.ThemeArg
---@field width? integer
---@field relative? "editor"|"cursor"|"win"
---@field row? integer                     # only with relative="editor"; overrides the default centered placement
---@field col? integer                     # only with relative="editor"; overrides the default centered placement
---@field debounce? integer                # ms between the last keystroke and on_change (default 80)
---@field on_change fun(query: string)      # fired debounced as the user types
---@field on_submit? fun(query: string)     # <CR>
---@field on_cancel? fun()                  # <Esc>

--- Options for `kit.compare` / `kit.popup({ type = "compare" })`. See
--- lua/ui/kit/compare.lua's module doc for the SEARCH → MARKED →
--- COMPARE flow.
---@class Ui.Kit.CompareOpts
---@field items any[]                                  # candidates to pick from
---@field format_item? fun(item: any): any              # results-list line; default tostring
---@field query? fun(query: string, items: any[]): any[] # custom filter; default: substring match on format_item
---@field render fun(item: any, surface: Ui.Kit.Surface)  # required: paint `item` into `surface`
---@field clear? fun()                                  # called once before every state transition
---@field on_compare? fun(a: any, b: any)                # fires once with BOTH picks, before either render() call for COMPARE — the only point in this contract where a caller's render can know its sibling item, e.g. to scale two images relative to each other instead of each to its own pane
---@field mark_key? string                               # marks the first pick (default "<M-c>"); <CR> also works
---@field title? string
---@field theme? Ui.Kit.ThemeArg
---@field on_close? fun(a: any, b: any)                  # a/b = the two picks; b is nil on an aborted pick

--- Handle returned by `kit.compare`. `state`/`slots`/`move`/`mark`/`confirm`
--- mirror `kit.picker`'s handle shape so the state machine is directly
--- drivable/testable without simulating keypresses.
---@class Ui.Kit.CompareHandle
---@field close fun()
---@field state fun(): "search"|"marked"|"compare"
---@field slots fun(): table<string, Ui.Kit.Surface>
---@field move fun(delta: integer)
---@field mark fun()                                     # SEARCH only: freeze the highlighted item, enter MARKED
---@field confirm fun()                                  # SEARCH: same as mark; MARKED: pick the 2nd item, enter COMPARE

--- A `kit.chip` colour: a highlight-group name to tint from (theme-linked,
--- re-tints on `ColorScheme`), an explicit fixed pair (`"#rrggbb"` strings
--- or 24-bit numbers), or a zero-arg function returning either -- re-called
--- fresh on every `refresh`, same as `text`/`visible`. For a colour with no
--- single stable source (e.g. a statusline that switches *which* highlight
--- group it references as the mode changes, rather than one group whose own
--- colour changes). `nil` uses the chip's own default group.
---@alias Ui.Kit.ChipColor string|{ fg: string|integer, bg?: string|integer }|fun():(string|{ fg: string|integer, bg?: string|integer }|nil)

--- Options for `kit.chip.mount`.
---@class Ui.Kit.ChipOpts
---@field id string                              # stable key; a second `mount` with the same id re-configures it
---@field text? string|fun():string              # re-read on every `refresh`; "" hides the chip; embed `\n` for a multi-line box (height follows the line count)
---@field visible? boolean|fun():boolean         # default: derived from `text` being non-empty
---@field anchor? "bottom-left"|"bottom-right"|"top-left"|"top-right"  # default "bottom-left"
---@field shape? Ui.Kit.Preset|"dock_left"       # default "rounded_chip"; "classic" has no box at all (no border, no background); "dock_left" rounds every corner but the left one (see `dock`); old names ("rounded"/"rect"/"text") still accepted, see ui.kit.presets
---@field color? Ui.Kit.ChipColor
---@field zindex? integer                        # default 60
---@field dock? boolean                          # sit flush ON the statusline row (col 0, no gap) instead of floating just above it; degrades to the ordinary placement when there is no statusline row to dock against (`laststatus = 0`, or none active). Meant to pair with `shape = "dock_left"`, but independent of it.
---@field track_mode? boolean                    # refresh() this one chip on every `ModeChanged`, e.g. for a `color` function that tracks the current mode -- opt-in per chip, not a blanket autocmd
---@field row_offset? integer                    # default 0; added to the computed row after anchor/dock placement -- a plain per-chip nudge, e.g. to compensate for a specific host terminal's own rendering quirks without hardcoding that terminal's name anywhere in this module. Note: Neovim floating windows are clipped to the actual terminal grid -- a terminal's own OUTER padding (applied around that grid, e.g. WezTerm's `window_padding`) sits entirely outside anything a `col`/`row` value can reach, so this cannot compensate for that specific class of gap; it only ever repositions the chip within the grid Neovim can already draw into. Accepts a fractional number, but `:h nvim_open_win()`'s own `row`/`col` are documented to always round DOWN to the nearest integer in Neovim's builtin (non-multigrid) implementation -- the one a plain terminal client uses -- so e.g. `0.5` renders pixel-identical to `0`, not "half a cell". Pass an integer; a fractional value is accepted but never actually more precise than `math.floor()` of it.
---@field col_offset? integer                    # default 0; same as `row_offset`, applied to the computed column. Same clipped-to-the-grid and floor-to-integer caveats apply.
---@field min_width? integer                     # default 0 (no minimum); a floor under the box's normally content-derived width (longest rendered line + 2). Content wider than it still grows the box past it -- this only stops a short line (e.g. one glyph plus a mode letter) from rendering visibly cramped. Floored to a non-negative integer; an invalid value (non-number, NaN, +-Infinity, negative) sanitizes to 0 rather than crashing `mount()`.

--- Options for `kit.chip.pulse`.
---@class Ui.Kit.ChipPulseOpts
---@field color? Ui.Kit.ChipColor                # default: link "DiagnosticWarn"
---@field duration_ms? integer                   # default 300

---@class Ui.Kit.ChipModule
---@field mount fun(opts: Ui.Kit.ChipOpts): string
---@field refresh fun(id: string)
---@field pulse fun(id: string, opts?: Ui.Kit.ChipPulseOpts)
---@field unmount fun(id: string)
---@field active fun(): string[]

--- Options for `kit.setup`.
---@class Ui.Kit.SetupOpts
---@field default? string                       # active preset name
---@field presets? table<string, table>         # user-registered presets

--- The `ui.kit` module.
---@class Ui.Kit
---@field setup fun(opts?: Ui.Kit.SetupOpts)
---@field popup fun(opts: table): any            # dispatch on opts.type
---@field note fun(opts: Ui.Kit.NoteOpts): Ui.Kit.Surface|nil
---@field viewer fun(opts: Ui.Kit.ViewerOpts): Ui.Kit.Surface|nil  # read-only info panel, closes on focus loss
---@field message_log fun(opts: Ui.Kit.MessageLog.Opts): Ui.Kit.MessageLog.Handle|nil  # paginated/collapsible time-ordered entry list
---@field toast fun(opts: table): Ui.Kit.Surface|nil    # ephemeral corner message
---@field input fun(opts: Ui.Kit.InputOpts): Ui.Kit.Surface|nil    # single-line insert-mode prompt (secret = true masks it)
---@field live_input fun(opts: Ui.Kit.LiveInputOpts): Ui.Kit.Surface|nil  # debounced on_change as you type
---@field form fun(opts: Ui.Kit.FormOpts): Ui.Kit.Surface|nil  # sequential multi-field prompt
---@field sheet fun(opts: Ui.Kit.SheetOpts): Ui.Kit.Sheet|nil     # every field at once in one float, inline validation, Submit/Cancel buttons
---@field select fun(opts: table): any                       # native themed list chooser (single/multi)
---@field prompt fun(opts: table): any                       # ask: confirm (yes/no) or text
---@field picker fun(opts: table): table|nil                 # interactive picker (prompt drives results)
---@field confirm fun(opts: table): Ui.Kit.Surface|nil    # button-confirm dialog (horizontal buttons)
---@field menu fun(opts: table): Ui.Kit.Surface|nil        # cursor-anchored action list (label → callback)
---@field compare fun(opts: Ui.Kit.CompareOpts): Ui.Kit.CompareHandle|nil  # pick two items, view them side by side
---@field progress fun(opts: table): table                     # passthrough to lib.nvim.progress.create
---@field sync fun(open_fn: fun(opts: table): any, opts: table, timeout_ms: integer|nil): any  # vim.wait bridge for on_submit/on_cancel components; full signature (incl. the two boolean returns) is on lua/ui/kit/init.lua's M.sync
---@field preview fun(): integer, integer                       # open the live theme playground (also :KitPreview)
---@field surface Ui.Kit.SurfaceModule
---@field theme Ui.Kit.ThemeModule
---@field layout Ui.Kit.LayoutModule
---@field chooser Ui.Kit.ChooserModule  # low-level escape hatch behind kit.select -- see its own doc comment
---@field chip Ui.Kit.ChipModule  # persistent editor-corner status chip (mount/refresh/pulse/unmount)

--- `ui.kit.buttons`: the row layout, focus highlight and mouse hit-test that
--- `kit.confirm` and the button row of `kit.input`/`kit.form` share. Stateless.
---@class Ui.Kit.ButtonsModule
---@field box fun(label: string): string  # "[ label ]"
---@field row_width fun(labels: string[]): integer  # display width of the whole row
---@field layout fun(labels: string[], width: integer, row: integer): string, Ui.Kit.ButtonRange[]
---@field paint fun(buf: integer|nil, ns: integer, ranges: Ui.Kit.ButtonRange[], focus: integer|nil)  # KitSelection on the focused box; nil focus = none
---@field hit fun(ranges: Ui.Kit.ButtonRange[], winid: integer): integer|nil, table|nil  # button under the mouse; second value is getmousepos() when the click was in `winid`
---@field wrap fun(focus: integer, delta: integer, n: integer): integer

---@class Ui.Kit.SurfaceModule
---@field open fun(opts?: Ui.Kit.SurfaceOpts): Ui.Kit.Surface|nil

--- The chooser `kit.select` delegates to; see `kit.chooser`'s doc comment
--- in lua/ui/kit/init.lua for when to reach for this directly.
---@class Ui.Kit.ChooserModule
---@field open fun(opts: table): Ui.Kit.Surface|nil
---@field set_items fun(opts: table): boolean  # replace the open list in place (same window); false when nothing is open
---@field close fun()
---@field is_open fun(): boolean
---@field move fun(delta: integer)
---@field toggle fun()
---@field submit fun()
---@field current_index fun(): integer|nil
---@field current_item fun(): any

--- Geometry for one slot (an nvim_open_win config).
---@class Ui.Kit.Slot
---@field relative "editor"
---@field row integer
---@field col integer
---@field width integer
---@field height integer

--- A mounted layout group.
---@class Ui.Kit.Group
---@field slots table<string, Ui.Kit.Surface>
---@field close fun()

---@class Ui.Kit.LayoutModule
---@field compute fun(spec: table): { slots: table<string, Ui.Kit.Slot>, outer: table }
---@field mount fun(spec: table, opts?: table): Ui.Kit.Group
---@field template fun(name: string, opts?: table): Ui.Kit.Group|nil
---@field templates table<string, { spec: table }>

---@class Ui.Kit.ThemeModule
---@field resolve fun(theme?: Ui.Kit.ThemeArg): Ui.Kit.Theme
---@field apply fun(winid: integer, resolved: Ui.Kit.Theme)
---@field materialize fun(resolved: Ui.Kit.Theme)   # define the Kit* highlight groups (no window)
---@field border_glyphs fun(resolved: Ui.Kit.Theme): table|nil  # box-drawing glyph set, or nil (borderless)
---@field setup fun(opts?: Ui.Kit.SetupOpts)
---@field presets fun(): string[]
---@field default fun(): string  # name of the currently active default preset

return {}
