-- See TESTS/config_spec.lua for what these three suppressions cover and why.
---@diagnostic disable: need-check-nil, undefined-field, discard-returns

--- `ui.statusline.modules.tasks_counter` -- the opt-in "T:7" segment. Every
--- spec that reads files builds its own temporary vault; the real one is
--- never touched.

local config = require("ui.statusline.modules.tasks_counter.config")
local source = require("ui.statusline.modules.tasks_counter.source")
local core = require("ui.statusline.modules.tasks_counter.core")
local render = require("ui.statusline.modules.tasks_counter")

local INDEX = table.concat({
  "<!-- GENERATED by :MyPlugins tasks index — do not edit; edit tasks/*.md -->",
  "# demo.nvim — offene Tasks (5)",
  "",
  "| Status | Prio | Effort | Task | Zusammenfassung |",
  "|---|---|---|---|---|",
  "| decision | 3 | M | [a](tasks/a.md) | a question with a \\| pipe |",
  "| open | 1 | XS | [b](tasks/b.md) | urgent |",
  "| open | – | S | [c](tasks/c.md) | no prio |",
  "| blocked | 1 | S | [d](tasks/d.md) | stuck |",
  "| parked | 2 | M | [e](tasks/e.md) | later |",
  "",
}, "\n")

---@param path string
---@param text string
local function write(path, text)
  vim.fn.mkdir(vim.fs.dirname(path), "p")
  local f = assert(io.open(path, "wb"))
  f:write(text)
  f:close()
end

---@param status string
---@param prio string|nil
---@return string
local function task_file(status, prio)
  return table.concat({
    "---",
    "title: x",
    "status: " .. status,
    prio and ("prio: " .. prio) or "kind: bug",
    "---",
    "",
    "body",
  }, "\n")
end

--- Wait for the async refresh to land.
local function settle()
  assert.is_true(vim.wait(3000, function()
    return core.snapshot().loaded_at ~= nil and not core.snapshot().scheduled
  end, 10))
end

describe("ui.statusline.modules.tasks_counter.source", function()
  it("parse_index counts table rows by status and prio, ignoring header and separator", function()
    local tasks = source.parse_index(INDEX)
    assert.equals(5, #tasks)
    assert.equals("decision", tasks[1].status)
    assert.equals(3, tasks[1].prio)
    assert.is_nil(tasks[3].prio) -- an en dash is "no prio"
    assert.equals("parked", tasks[5].status)
  end)

  it("parse_index survives CRLF and garbage", function()
    assert.equals(5, #source.parse_index((INDEX:gsub("\n", "\r\n"))))
    assert.same({}, source.parse_index("nothing | here\n| x | y |\n"))
    assert.same({}, source.parse_index(""))
  end)

  it("parse_task reads status and prio from the frontmatter only", function()
    assert.same({ status = "open", prio = 2 }, source.parse_task(task_file("open", "2")))
    assert.same({ status = "blocked" }, source.parse_task(task_file("blocked")))
    assert.is_nil(source.parse_task("no frontmatter\nstatus: open\n"))
    assert.is_nil(source.parse_task(task_file("done", "1")))
    -- a `status:` in the body must not count
    assert.is_nil(source.parse_task("---\ntitle: x\n---\nstatus: open\n"))
  end)

  it("tally counts only the configured statuses", function()
    local tasks = source.parse_index(INDEX)
    local counts = source.tally(tasks, { "open", "doing", "blocked", "decision" }, 1)
    assert.same({ total = 4, urgent = 2, blocked = 1 }, counts)
    assert.equals(5, source.tally(tasks, { "open", "blocked", "decision", "parked" }, 1).total)
    assert.equals(2, source.tally(tasks, { "open" }, 1).total)
  end)
end)

describe("ui.statusline.modules.tasks_counter.config", function()
  after_each(function()
    config.setup(nil)
  end)

  it("ships DEFAULTS with every documented option", function()
    for _, key in ipairs({
      "areas",
      "source",
      "statuses",
      "ttl_ms",
      "prefix",
      "hide_zero",
      "breakdown",
      "urgent_prio",
      "watch_writes",
      "max_files",
    }) do
      assert.is_not_nil(config.DEFAULTS[key], key)
    end
  end)

  it("keeps the default for a field of the wrong type instead of throwing", function()
    assert.has_no.errors(function()
      config.setup({ ttl_ms = "soon", statuses = { "nope" }, source = 3, vault = 5, bogus = true })
    end)
    local cfg = config.get()
    assert.equals(config.DEFAULTS.ttl_ms, cfg.ttl_ms)
    assert.same(config.DEFAULTS.statuses, cfg.statuses)
    assert.equals("auto", cfg.source)
    assert.is_nil(cfg.vault)
  end)

  it("rejects an area that could leave the vault", function()
    assert.is_false(config.valid_area("../x"))
    assert.is_false(config.valid_area("a/b"))
    assert.is_false(config.valid_area("a\\b"))
    assert.is_false(config.valid_area(""))
    assert.is_true(config.valid_area("ui.nvim"))
  end)

  it("derives the area from the git root's folder name, via areas aliases", function()
    config.setup({})
    local derived = config.resolve_area(config.get())
    assert.is_not_nil(derived)
    config.setup({ areas = { [derived] = "aliased" } })
    assert.equals("aliased", config.resolve_area(config.get()))
    config.setup({ area = "fixed" })
    assert.equals("fixed", config.resolve_area(config.get()))
    config.setup({
      area = function()
        return "from-fn"
      end,
    })
    assert.equals("from-fn", config.resolve_area(config.get()))
    config.setup({
      area = function()
        error("boom")
      end,
    })
    assert.is_nil(config.resolve_area(config.get()))
  end)

  it("resolves the vault from opts, then $TASKS_VAULT; nil when neither exists", function()
    local vault = vim.fn.tempname()
    vim.fn.mkdir(vault, "p")
    local saved_tv, saved_rd = vim.env.TASKS_VAULT, vim.env.REPOS_DIR
    vim.env.TASKS_VAULT = nil
    vim.env.REPOS_DIR = nil

    assert.is_nil(config.resolve_vault({}))
    assert.equals(vim.fs.normalize(vault), config.resolve_vault({ vault = vault }))
    vim.env.TASKS_VAULT = vault
    assert.equals(vim.fs.normalize(vault), config.resolve_vault({}))
    -- a configured but missing vault falls through to the env var
    assert.equals(vim.fs.normalize(vault), config.resolve_vault({ vault = vault .. "-missing" }))

    vim.env.TASKS_VAULT, vim.env.REPOS_DIR = saved_tv, saved_rd
    vim.fn.delete(vault, "rf")
  end)
end)

describe("ui.statusline.modules.tasks_counter (render)", function()
  local vault
  -- The relative `lua/` rtp entry of scripts/minimal_init.lua breaks if a
  -- failed spec leaves the cwd elsewhere, so it is restored unconditionally.
  local start_cwd = vim.uv.cwd()

  before_each(function()
    vault = vim.fn.tempname()
    vim.fn.mkdir(vault, "p")
    core._reset()
  end)

  after_each(function()
    vim.cmd("cd " .. vim.fn.fnameescape(start_cwd))
    config.setup(nil)
    core._reset()
    vim.fn.delete(vault, "rf")
  end)

  it("renders empty and does not error without any vault", function()
    config.setup({ vault = vault .. "-missing", area = "demo.nvim" })
    local saved = vim.env.TASKS_VAULT
    vim.env.TASKS_VAULT = nil
    local saved_rd = vim.env.REPOS_DIR
    vim.env.REPOS_DIR = nil

    assert.equals("", render())
    settle()
    assert.equals("", render())
    assert.is_nil(core.snapshot().counts)

    vim.env.TASKS_VAULT, vim.env.REPOS_DIR = saved, saved_rd
  end)

  it("renders empty for an area the vault does not have", function()
    config.setup({ vault = vault, area = "ghost.nvim" })
    render()
    settle()
    assert.equals("", render())
  end)

  it("does not read anything during the first render, only after the schedule", function()
    write(vault .. "/demo.nvim/ROADMAP/TASKS.md", INDEX)
    config.setup({ vault = vault, area = "demo.nvim" })

    assert.equals("", render()) -- cold: nothing cached yet, refresh merely queued
    assert.is_true(core.snapshot().scheduled)
    settle()
    assert.is_truthy(render():find("T:4", 1, true))
  end)

  it("counts from the generated TASKS.md and shows the breakdown on request", function()
    write(vault .. "/demo.nvim/ROADMAP/TASKS.md", INDEX)
    config.setup({ vault = vault, area = "demo.nvim", breakdown = true })

    render()
    settle()
    local out = render()
    assert.is_truthy(out:find("T:4", 1, true), out)
    assert.is_truthy(out:find("P1:2", 1, true), out)
    assert.is_truthy(out:find("B:1", 1, true), out)
    assert.is_truthy(out:find("%#St_TasksUrgent#", 1, true), out)
  end)

  it("omits the breakdown by default and escapes % in the prefix", function()
    write(vault .. "/demo.nvim/ROADMAP/TASKS.md", INDEX)
    config.setup({ vault = vault, area = "demo.nvim", prefix = "100%:" })

    render()
    settle()
    local out = render()
    assert.is_truthy(out:find("100%%:4", 1, true), out)
    assert.is_nil(out:find("P1:", 1, true))
  end)

  it("falls back to tasks/*.md without a TASKS.md; honours source=tasks_dir", function()
    local dir = vault .. "/demo.nvim/ROADMAP/tasks/"
    write(dir .. "a.md", task_file("open", "1"))
    write(dir .. "b.md", task_file("doing", "2"))
    write(dir .. "c.md", task_file("parked", "3"))
    write(dir .. "notes.txt", "not markdown")
    write(dir .. "broken.md", "no frontmatter")

    config.setup({ vault = vault, area = "demo.nvim" })
    render()
    settle()
    assert.same({ total = 2, urgent = 1, blocked = 0 }, core.snapshot().counts)

    config.setup({
      vault = vault,
      area = "demo.nvim",
      source = "tasks_dir",
      statuses = { "parked" },
    })
    render()
    settle()
    assert.equals(1, core.snapshot().counts.total)
  end)

  it("hides zero by default and shows it with hide_zero = false", function()
    write(vault .. "/demo.nvim/ROADMAP/tasks/p.md", task_file("parked"))
    config.setup({ vault = vault, area = "demo.nvim" })
    render()
    settle()
    assert.equals(0, core.snapshot().counts.total)
    assert.equals("", render())

    config.setup({ vault = vault, area = "demo.nvim", hide_zero = false })
    render()
    settle()
    assert.is_truthy(render():find("T:0", 1, true))
  end)

  it("takes a pluggable source function; a throwing one ends as an empty segment", function()
    config.setup({
      vault = vault,
      area = "demo.nvim",
      source = function(ctx, done)
        assert.equals("demo.nvim", ctx.area)
        done({ { status = "open", prio = 1 }, { status = "open" }, { status = "done" } })
      end,
    })
    render()
    settle()
    assert.same({ total = 2, urgent = 1, blocked = 0 }, core.snapshot().counts)

    config.setup({
      vault = vault,
      area = "demo.nvim",
      source = function()
        error("boom")
      end,
    })
    render()
    settle()
    assert.is_nil(core.snapshot().counts)
    assert.equals("", render())
  end)

  it("reuses the result within the TTL and re-reads after it", function()
    write(vault .. "/demo.nvim/ROADMAP/TASKS.md", INDEX)
    local calls = 0
    config.setup({
      vault = vault,
      area = "demo.nvim",
      ttl_ms = 150,
      source = function(_, done)
        calls = calls + 1
        done({ { status = "open" } })
      end,
    })
    render()
    settle()
    assert.equals(1, calls)
    render()
    render()
    vim.wait(30)
    assert.equals(1, calls)

    vim.wait(250)
    render() -- stale now: queues one refresh, still shows the old number
    assert.is_truthy(render():find("T:1", 1, true))
    settle()
    assert.equals(2, calls)
  end)

  it("drops the count on DirChanged and re-reads for the new project", function()
    local seen = {}
    config.setup({
      vault = vault,
      area = "demo.nvim",
      source = function(_, done)
        seen[#seen + 1] = vim.uv.cwd()
        done({ { status = "open" }, { status = "open" } })
      end,
    })
    render()
    settle()
    assert.equals(2, core.snapshot().counts.total)

    local orig = vim.uv.cwd()
    local other = vim.fn.tempname()
    vim.fn.mkdir(other, "p")
    vim.cmd("cd " .. vim.fn.fnameescape(other))
    -- DirChanged fired synchronously: the old project's number is gone at once
    assert.is_nil(core.snapshot().counts)
    assert.equals("", render())
    settle()
    assert.equals(2, #seen)
    assert.equals(2, core.snapshot().counts.total)

    vim.cmd("cd " .. vim.fn.fnameescape(orig))
    vim.fn.delete(other, "rf")
  end)

  it("discards a slow read that was overtaken by an invalidate", function()
    local release
    config.setup({
      vault = vault,
      area = "demo.nvim",
      source = function(_, done)
        release = function()
          done({ { status = "open" } })
        end
      end,
    })
    render()
    assert.is_true(vim.wait(1000, function()
      return release ~= nil
    end, 5))
    local stale_release = release
    core.invalidate() -- project switched while the first read is in flight
    release = nil
    assert.is_true(vim.wait(1000, function()
      return release ~= nil
    end, 5))

    stale_release() -- the old read finishes late ...
    vim.wait(50)
    assert.is_nil(core.snapshot().counts) -- ... and must not be shown
    release()
    settle()
    assert.equals(1, core.snapshot().counts.total)
  end)

  it("re-reads after a Markdown file inside the vault is saved", function()
    write(vault .. "/demo.nvim/ROADMAP/TASKS.md", INDEX)
    config.setup({ vault = vault, area = "demo.nvim", ttl_ms = 3600000 })
    render()
    settle()
    assert.equals(4, core.snapshot().counts.total)

    write(
      vault .. "/demo.nvim/ROADMAP/TASKS.md",
      "| Status | Prio |\n|---|---|\n| open | 1 | x |\n"
    )
    vim.cmd("edit " .. vim.fn.fnameescape(vault .. "/demo.nvim/ROADMAP/TASKS.md"))
    vim.cmd("silent write")
    assert.is_true(vim.wait(3000, function()
      local c = core.snapshot().counts
      return c ~= nil and c.total == 1 and not core.snapshot().scheduled
    end, 10))
    vim.cmd("bwipeout!")
  end)

  it("uses highlight groups that exist before the first render", function()
    require("ui.statusline.highlights").apply()
    for _, group in ipairs({ "St_TasksCounter", "St_TasksUrgent", "St_TasksBlocked" }) do
      local hl = vim.api.nvim_get_hl(0, { name = group, link = false })
      assert.is_not_nil(hl.fg, group .. " has no fg")
    end
  end)

  it("is in the statusline catalog and ui.setup stores its options", function()
    local found
    for _, entry in ipairs(require("ui.statusline.catalog")) do
      if entry.key == "tasks_counter" then
        found = entry
      end
    end
    assert.is_not_nil(found)
    assert.is_false(found.builtin)

    require("ui").setup({ tasks = { prefix = "Tasks ", breakdown = true } })
    assert.equals("Tasks ", config.get().prefix)
    assert.is_true(config.get().breakdown)
  end)
end)
